version: '3'
services:
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: 4kyjt4ap
      MYSQL_DATABASE: blog_development
      MYSQL_USER: app
      MYSQL_PASSWORD: samolet1
  web:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - "mysql"